spring:
 application:
     name: notification-email
 jpa:
   hibernate:
    ddl-auto: create-drop
   show-sql: true
 datasource:
  url: jdbc:postgresql://localhost:5432/notificacaoemaildb 
  username: calderarogustavo
  password: Gusang_20011  
 mail:
    host: smtp.gmail.com
    port: 587
    username: calderarogustavo@gmail.com
    password: "ingu xzop tjgo seoq"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true	