spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: service-route
          uri: lb://service
          predicates:
            - Path=/api/v1/services-registry/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY
                method: GET,PUT
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 30ms
                  factor: 2
                timeout: 400ms
            - name: CircuitBreaker
              args:
                name: service-route-circuit-breaker
                statusCodes:
                  - 500
                  - 502
                  - 504

        - id: services-route
          uri: lb://services
          predicates:
            - Path=/api/v1/services/**

        - id: service-public-route
          uri: lb://service
          predicates:
            - Path=/public/services
            - Method=GET
          filters:
            - RewritePath=/public/services, /api/v1/services
            - RemoveJsonAttributesResponseBody=pendingServices,pendingServicesQuantity,phone,true

        - id: service-public-segments-route
          uri: lb://service
          predicates:
            - Path=/public/services/**
            - Method=GET
          filters:
            - RewritePath=/public/services/?(?<segment>.*), /api/v1/services/${segment}
            - RemoveJsonAttributesResponseBody=pendingServices,pendingServicesQuantity,phone,true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      services-route-circuit-breaker:
        baseConfig: default
        waitDurationInOpenState: 5000
