server.port: 8081

spring:
 application:
   name: atendimento
 jpa:
   hibernate:
      ddl-auto: update
   show-sql: false
 datasource:
   url: jdbc:postgresql://localhost:5432/atendimentodb  	 
   username: calderarogustavo
   password: Gusang_20011